baseurl = "https://gohugo.io/"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3

googleAnalytics = ""

theme = "strange-case"

[params]
	colorScheme = "scheme-darkbrown"
	dateformat = "Jan 2, 2006"
	description = "A Hugo Theme built with Bootstrap"
	sidebarFreeText = "A optional paragraph of free text. Set to blank in config.toml to clear..."
	piwikSiteID = ""
	piwikURL = ""

[[menu.main]]
	name = "Hugo"
	post = "<span class='glyphicon glyphicon-fire'></span>"
	url = "http://gohugo.io"

[[menu.main]]
	name = "Bootstrap"
	post = "<span class='glyphicon glyphicon-ok'></span>"
	url = "http://getbootstrap.com"
